DROP DATABASE INSTITUTO;

CREATE DATABASE INSTITUTO;
USE INSTITUTO; 

CREATE TABLE LOCALIDAD(
CODLOCALIDAD INT AUTO_INCREMENT,
NOMBRE VARCHAR(50),
PRIMARY KEY(CODLOCALIDAD)
);

CREATE TABLE RANGODIRECTIVO(
CODRANGODIR INT AUTO_INCREMENT,
NOMBRE VARCHAR(50),
 PRIMARY KEY(CODRANGODIR) 
);

CREATE TABLE PROFESIONES(
CODPROFESION INT AUTO_INCREMENT,
NOMBRE VARCHAR(35),
DURACIONPROF INT,
CSTMATRICULA INT,
CUOTASTOTAL INT,
VALORXCTA INT,
PRIMARY KEY(CODPROFESION)
);

CREATE TABLE DOCENTE(
IDDOCENTE INT AUTO_INCREMENT,
APELLIDO VARCHAR(35),
NOMBRE VARCHAR(35),
CODLOCALIDAD INT,
DOMICILIO VARCHAR(50),
TEL INT,
EMAIL VARCHAR(50),
DNI INT,
GENERO VARCHAR(10),
FECHAING DATE,
CODPROFESION INT,
CODRANGODIR INT,
PRIMARY KEY(IDDOCENTE),
FOREIGN KEY(CODLOCALIDAD) REFERENCES LOCALIDAD(CODLOCALIDAD), 
FOREIGN KEY(CODRANGODIR) REFERENCES RANGODIRECTIVO(CODRANGODIR),
FOREIGN KEY(CODPROFESION) REFERENCES PROFESIONES(CODPROFESION)
);

CREATE TABLE PLANILLA(
CODPLANILLA INT AUTO_INCREMENT,
FECHA DATE,
TURNO VARCHAR(15),
PRIMARY KEY(CODPLANILLA)
);

CREATE TABLE PLANILLADLLE(
CODPLANILLADLLE INT AUTO_INCREMENT,
CODPLANILLA INT,
IDDOCENTE INT,
HORALLEGADA TIME,
HORARETIRO TIME,
ESTADO VARCHAR(20),
PRIMARY KEY(CODPLANILLADLLE),
FOREIGN KEY(CODPLANILLA) REFERENCES PLANILLA(CODPLANILLA), 
FOREIGN KEY(IDDOCENTE) REFERENCES DOCENTE(IDDOCENTE)  
);

CREATE TABLE MOTIVOLICENCIA(
CODMOTIVO INT AUTO_INCREMENT,
MOTIVO VARCHAR(80),
PRIMARY KEY(CODMOTIVO)
);

CREATE TABLE LICENCIA(
CODLICENCIA INT AUTO_INCREMENT,
IDDOCENTE INT,
FECHAEMISION DATE,
DURACION VARCHAR(80),
CODMOTIVO INT,
PRIMARY KEY(CODLICENCIA),
FOREIGN KEY(IDDOCENTE) REFERENCES DOCENTE(IDDOCENTE),
FOREIGN KEY(CODMOTIVO) REFERENCES MOTIVOLICENCIA(CODMOTIVO)  
);

CREATE TABLE SUELDO(
CODSUELDO INT AUTO_INCREMENT,
CODRANGODIR INT,
SUELDOBASE INT,
PRIMARY KEY(CODSUELDO),
FOREIGN KEY(CODRANGODIR) REFERENCES RANGODIRECTIVO(CODRANGODIR)  
);

CREATE TABLE RECIBO(
CODRECIBO INT AUTO_INCREMENT,
IDDOCENTE INT,
FECHA DATE,
HORA TIME,
MONTOTOTAL INT,
PERIODOPAGO VARCHAR(40),
PRIMARY KEY(CODRECIBO),
FOREIGN KEY(IDDOCENTE) REFERENCES DOCENTE(IDDOCENTE)
);

CREATE TABLE RECIBODLLE(
CODRECIBODLLE INT AUTO_INCREMENT,
CODRECIBO INT,
REFERENCIA VARCHAR(50),
SUBTOTAL INT,
PRIMARY KEY(CODRECIBODLLE),
FOREIGN KEY(CODRECIBO) REFERENCES RECIBO(CODRECIBO) 
);

CREATE TABLE USUARIO(
CODUSUARIO INT AUTO_INCREMENT,
DNI INT,
CONTRASENIA VARCHAR(30),
PRIMARY KEY(CODUSUARIO)
);

CREATE TABLE TrnINSCRIPCIONES(
CODTURNO INT AUTO_INCREMENT,
FECHA DATE,
HORA TIME,
DNI INT,
APELLIDO VARCHAR(35),
NOMBRE VARCHAR(35),
TEL INT,
CODPROFESION INT,
PRIMARY KEY(CODTURNO),
FOREIGN KEY(CODPROFESION) REFERENCES PROFESIONES(CODPROFESION)
);

CREATE TABLE ALUMNOS(
IDALUMNO INT AUTO_INCREMENT,
APELLIDO VARCHAR(35),
NOMBRE VARCHAR(35),
CODLOCALIDAD INT,
DOMICILIO VARCHAR(50),
TEL INT,
EMAIL VARCHAR(35),
DNI INT,
GENERO CHAR(10),
ESTADO CHAR(20),
MATRICULACION BOOLEAN,
CUOTASRESTANTES INT,
CUOTASPAGADAS INT,
FECHAINICIO DATE,
PRIMARY KEY(IDALUMNO),
FOREIGN KEY(CODLOCALIDAD) REFERENCES LOCALIDAD(CODLOCALIDAD)
);

CREATE TABLE PAGO(
CODPAGOM INT AUTO_INCREMENT,
IDALUMNO INT,
FECHA DATE,
MONTO INT,
REFERENCIAS VARCHAR(50),
PRIMARY KEY(CODPAGOM),
FOREIGN KEY(IDALUMNO) REFERENCES ALUMNOS(IDALUMNO)
);

CREATE TABLE CLASES(
NROCLASE INT AUTO_INCREMENT,
CODPROFESION INT,
MAXCANTALUMNOS INT,
IDDOCENTE INT,
PRIMARY KEY(NROCLASE),
FOREIGN KEY(IDDOCENTE) REFERENCES DOCENTE(IDDOCENTE),
FOREIGN KEY(CODPROFESION) REFERENCES PROFESIONES(CODPROFESION)
);

CREATE TABLE ALUMNOCLASE(
NROCLASE INT,
IDALUMNO INT,
PRIMARY KEY(NROCLASE, IDALUMNO),
FOREIGN KEY(IDALUMNO) REFERENCES ALUMNOS(IDALUMNO),
FOREIGN KEY(NROCLASE) REFERENCES CLASES(NROCLASE)
);

CREATE TABLE CALIFICACIONES(
IDCALIF INT AUTO_INCREMENT,
NROCLASE INT,
IDALUMNO INT,
NombreTema VARCHAR(50),
NroNota INT,
PRIMARY KEY(IDCALIF),
FOREIGN KEY(NROCLASE) REFERENCES CLASES(NROCLASE),
FOREIGN KEY(IDALUMNO) REFERENCES ALUMNOS(IDALUMNO)
);

CREATE TABLE PLANILLA_ALUMNOS(
CODPLLA_ALUMNOS INT AUTO_INCREMENT,
NROCLASE INT,
FECHA DATE,
IDALUMNO INT,
ESTADO VARCHAR(20),
PRIMARY KEY(CODPLLA_ALUMNOS),
FOREIGN KEY(NROCLASE) REFERENCES CLASES(NROCLASE),
FOREIGN KEY(IDALUMNO) REFERENCES ALUMNOS(IDALUMNO)
);
